twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        home_path: "%app.path.home%"
        categories_path: "%app.path.categories%"
        slider_path: "%app.path.slider%"
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']