parameters:
    app.path.home: /images/home
    app.path.annonce: /images/annonce
    app.path.categories: /images/categories
    app.path.slider: /images/slider
    app.path.user: /images/useradmin

vich_uploader:
    db_driver: orm
    mappings:
        home:
            uri_prefix: /images/home
            upload_destination: "%kernel.project_dir%/public/images/home"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        categories:
            uri_prefix: /images/categories
            upload_destination: "%kernel.project_dir%/public/images/categories"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 
        slider:
            uri_prefix: /images/slider
            upload_destination: "%kernel.project_dir%/public/images/slider"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true  
        annonce:
            uri_prefix: /images/annonce
            upload_destination: "%kernel.project_dir%/public/images/annonce"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true       
        user:
            uri_prefix: /images/useradmin
            upload_destination: "%kernel.project_dir%/public/images/useradmin"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true                     
            

